### PR TITLE
Force to Use strict types in PHP code

### PR DESCRIPTION
**Pull request by plopesc**
https://architecture.lullabot.com/adr/20211201-use-strict-types-in-php-code/

### CODE REVIEW

**Review by justafish — APPROVED** [review]
Thanks!

**Comment by deviantintegral** [comment]
How will this apply to existing code we inherit that doesn't have strict types enabled? Is there a way to get phpstan to only evaluate new or changed files for a tests?

**Comment by justafish** [comment]
I guess no differently from code we inherit that violates any other rule - fix it when bringing in this new rule, or disable the test/add exceptions in comments until it can be fixed

**Comment by justafish** [comment]
Test isn't passing due to #226

**Pull request merged**
