### PR TITLE
DO NOT MERGE: Empty commit

### PR DESCRIPTION
**Pull request by mrdavidburns**
Checking Tugboat Build

### CODE REVIEW

**Comment by mrdavidburns** [comment]
Confirming that sessions table doesn't exist.

```
MariaDB [tugboat]> show tables;
+----------------------------------+
| Tables_in_tugboat                |
+----------------------------------+
| block_content                    |
| block_content__body              |
| block_content_field_data         |
| block_content_field_revision     |
| block_content_revision           |
| block_content_revision__body     |
| cache_bootstrap                  |
| cache_config                     |
| cache_container                  |
| cache_default                    |
| cache_discovery                  |
| cachetags                        |
| comment                          |
| comment__comment_body            |
| comment_entity_statistics        |
| comment_field_data               |
| config                           |
| file_managed                     |
| file_usage                       |
| help_search_items                |
| history                          |
| key_value                        |
| menu_link_content                |
| menu_link_content_data           |
| menu_link_content_field_revision |
| menu_link_content_revision       |
| menu_tree                        |
| node                             |
| node__body                       |
| node__comment                    |
| node__field_image                |
| node__field_tags                 |
| node_access                      |
| node_field_data                  |
| node_field_revision              |
| node_revision                    |
| node_revision__body              |
| node_revision__comment           |
| node_revision__field_image       |
| node_revision__field_tags        |
| path_alias                       |
| path_alias_revision              |
| router                           |
| search_dataset                   |
| search_index                     |
| search_total                     |
| semaphore                        |
| sequences                        |
| shortcut                         |
| shortcut_field_data              |
| shortcut_set_users               |
| taxonomy_index                   |
| taxonomy_term__parent            |
| taxonomy_term_data               |
| taxonomy_term_field_data         |
| taxonomy_term_field_revision     |
| taxonomy_term_revision           |
| taxonomy_term_revision__parent   |
| user__roles                      |
| user__user_picture               |
| users                            |
| users_data                       |
| users_field_data                 |
| watchdog                         |
+----------------------------------+
64 rows in set (0.002 sec)
```

**Comment by deviantintegral** [comment]
```
# task --summary sync
task: sync

Sync a database from production and import it

commands:
 - ./vendor/bin/drush site:install -y
 - echo "🧹 Sanitising database"
 - ./vendor/bin/drush sql:sanitize --yes
 - ```
 - 
@mrdavidburns I think this is a Drupal 10.3 change: https://www.drupal.org/node/3431286

`\Drupal\Core\Session\SessionHandler` now creates the table the first time as needed. Since we're calling sanitize before trying to log in, the table isn't there.

I think Drush needs to be updated so sql:sanitize will fail gracefully if the sessions table hasn't been created yet.

**Comment by penyaskito** [comment]
Drush is already updated on HEAD: https://github.com/drush-ops/drush/blob/13.x/src/Commands/sql/sanitize/SanitizeSessionsCommands.php

**Comment by penyaskito** [comment]
This has been backported to drush 12.x, maybe not released yet? https://github.com/drush-ops/drush/issues/6041

**Comment by beto-aveiga** [comment]
@mrdavidburns, here is the PR for Drush 13. PR Checks are passing.
https://github.com/Lullabot/drainpipe/pull/607
I'm unclear if that is what you need, and if so, what would be next.

**Comment by mrdavidburns** [comment]
Closing in favor of #608

**Pull request closed without merging**
