### PR TITLE
feat(twig): support storybook twig extension in linting

### PR DESCRIPTION
**Pull request by bronzehedwick**
fixes: #615 

The automatic twig linting throws a fatal error when the Storybook module is present, as the static tests don't bootstrap Drupal to discover twig extensions. Since bootstrapping Drupal is expensive, instead check and load the twig extension manually.

### CODE REVIEW

**Comment by deviantintegral** [comment]
The test failed creating a Pantheon multidev environment with a 403. I'm rerunning in case it was a transient error. I don't think it could have affected this PR.

**Review by deviantintegral — APPROVED** [review]

**Comment by mrdavidburns** [comment]
@deviantintegral I see you approved this. Does that mean the failed `Testing Github Action` is unrelated to this change?

```
Run source .github/actions/drainpipe/set-env/bash_aliases
Host *.drush.in
    StrictHostKeyChecking no
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
Run export GITHUB_DEPLOYMENT=$(curl -f -X POST \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 55   [39](https://github.com/Lullabot/drainpipe/actions/runs/10113686533/job/27971019295?pr=613#step:15:43)6    0     0  100   220      0    948 --:--:-- --:--:-- --:--:--   948
curl: (22) The requested URL returned error: [40](https://github.com/Lullabot/drainpipe/actions/runs/10113686533/job/27971019295?pr=613#step:15:44)3
Created GitHub Deployment ID 
Error: Process completed with exit code 1.
Run curl -f -H "Authorization: token ***" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$GITHUB_DEPLOYMENT_ID/statuses -d "{\"state\":\"failure\"}"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 15   122    0     0  100    19      0     85 --:--:-- --:--:-- --:--:--    86
curl: (22) The requested URL returned error: 404
```

**Comment by deviantintegral** [comment]
@mrdavidburns yeah, it is. See there's a 403 from Terminus? This part of the code only runs in ddev in github actions.

But it is odd that https://github.com/Lullabot/drainpipe/pull/611 passed. I'm going to rerun.

**Comment by deviantintegral** [comment]
Ohhh this is because this was created from a fork, where we don't pass secrets on. Since I am confident this code isn't used in any Pantheon steps, I'm going to override and merge.

**Pull request merged**
