### PR TITLE
Avoids errors when Extracting PHARs in class BinaryInstaller.php line 214 (PharData decompressing)

### PR DESCRIPTION
**Pull request by beto-aveiga**
### Description

It avoids errors when extracting PHARs.
Possibly related to: https://bugs.php.net/bug.php\?id\=75101

More information in the linked ticket below.

### Solves
https://github.com/Lullabot/drainpipe/issues/135

### CODE REVIEW

**Comment by deviantintegral** [comment]
@beto-aveiga does https://github.com/Lullabot/drainpipe/pull/207 avoid this issue for you?

**Comment by beto-aveiga** [comment]
@deviantintegral 
I haven't tried it, but I checked the PR and think it won't work.
I updated the description of this PR so you know what issue it is solving.

**Comment by beto-aveiga** [comment]
Opening

**Comment by beto-aveiga** [comment]
@deviantintegral @justafish I just tried this today. I could replicate the PHAR extracting in Tugboat, then added it to the composer file and work. Please review this. Many thanks!

**Comment by beto-aveiga** [comment]
FYI this is the error I was having in Tugboat:
```
- Skip [web-root]/modules/README.txt: overridden in abcd/xyz.org-cms
- Skip [web-root]/profiles/README.txt: overridden in abcd/xyz.org-cms
- Skip [web-root]/themes/README.txt: overridden in abcd/xyz.org-cms
Scaffolding files for lullabot/drainpipe:
- Skip [project-root]/.env because it already exists and overwrite is false.
> cd web && patch -p1 <../patches/htaccess-modifications.patch
patching file .htaccess
Updating BLT template files...
> blt blt:update --ansi --no-interaction
> blt:init:shell-alias
The BLT alias is already installed and up to date.
BLT 12 is end-of-life and unmaintained. Upgrade immediately to the latest major release.
See https://docs.acquia.com/blt/#releases-and-versioning
.gitignore does not contain drainpipe ignores. Compare .gitignore in the root of your repository with /var/lib/tugboat/vendor/lullabot/drainpipe/scaffold/gitignore and update as needed.
🪠 [Drainpipe] vendor/lullabot/drainpipe/scaffold/env/dotenv.php' missing from autoload-dev files
Using cached version of task v3.24.0 (05315061a703fc656984315f25813560f06ecd0076b220d07e1ef39f7f00a586)

In BinaryInstaller.php line 214:
                                                                                                                                                                                     
Unable to add newly converted phar "/root/.composer/cache/files/lullabot/drainpipe/bin/task/3.24.0/task_linux_amd64.tar" to the list of phars, a phar with that name already exists  
                                                                                                                                                                                     
```

**Review by YesCT — COMMENTED** [review]
I read https://bugs.php.net/bug.php?id=75101 and I can see how this approach could be a fix for us.

I'm not sure how to reproduce the bug though.

**Comment by deviantintegral** [comment]
If you switch to global binaries as in the other PR, this code isn't called for task or local-security-checker.

However, this is still worth fixing given that's opt in and we need to support this setup until at least the next major version of Drainpipe.

**Comment by YesCT** [comment]
relates to https://github.com/Lullabot/drainpipe/issues/807

**Pull request closed without merging**
