### PR TITLE
Add task for quiet config status check

### PR DESCRIPTION
**Pull request by hawkeyetwolf**
I had need of this lovely little snippet (from the `test:config` task) elsewhere, so can we make it its own task?

### CODE REVIEW

**Comment by justafish** [comment]
@hawkeyetwolf thank you for the PR!

I'm a bit confused by the description to make it it's own task, as it's already it's own task :smile: (you can run `task test:config`). Could you expand on the use case a bit more please?

**Comment by hawkeyetwolf** [comment]
@justafish yes, totes on the `test:config` task (here's a corresponding PR over there https://github.com/Lullabot/drainpipe-dev/pull/34). But I wanted just the first half of it, so I can do additional work _if_ there are config changes.

Context: I'm making a convenience script (to put in the ddev `host` commands folder) to facilitate fully re-initializing your local environment (e.g., for testing PRs, pulling in changes, etc). The goal is to help onboarding devs of varying experience levels.

I'm calling it `refresh` and will probably submit it to drainpipe and/or https://github.com/drud/ddev-contrib to see if it's interesting to others. I thought about making it a Task but didn't for various reasons (open to input). Full script further down; here's the relevant snippet:
```
# Confirm reverting Drupal configuration changes.
has_config_changes () { ! ddev task drupal:config:check > /dev/null 2>&1 ; }
if  has_config_changes ; then
  printf '\nYour local environment has some Drupal configuration overrides:\n\n'
  ddev drush config:status
  confirm \
    'Discard these configuration overrides and proceed?' \
    'To preserve configuration changes, export them to code with "drush config:export", and either commit them to a different/temporary branch, or stash the changes with "git stash".'
fi
```
Usage:
```
╰─λ ddev refresh -h
Refreshes the local development environment. (shell host container command)

Usage:
ddev refresh [branch] [flags]

Examples:
"ddev refresh 123-fixes-things --no-restart --import-db"

Flags:
-h, --help           help for refresh
-i, --import-db      Import a Drupal database dump (downloads a fresh copy unless the "--use-existing" flag is given).
-A, --no-assets      Don't compile front-end assets (JS, CSS, etc).
-C, --no-composer    Don't run "composer install".
-G, --no-git-pull    Don't update the git branch.
-R, --no-restart     Don't restart ddev, e.g., because you know there have been no ddev configuration changes.
-U, --no-update      Don't run Drupal database updates, import configuration, or clear caches, etc.
-e, --use-existing   Import the existing/previously-downloaded database dump rather than downloading a new one.
-v, --verbose        Show more command output.
-y, --yes            Automaticallly answer "yes" to all confirmation prompts.

Global Flags:
-j, --json-output   If true, user-oriented output will be in JSON format.
```
Source:
```
╰─λ cat .ddev/commands/host/refresh
#!/usr/bin/env bash

# Initialize options variables.
skip_prompts=0
can_import_db=0
existing_sql=0
no_git_pull=0
no_restart=0
no_composer=0
no_assets=0
no_update=0
no_login=0

# Parse command flags and arguments. Adapted from
# https://stackoverflow.com/a/62616466
EOL=$(echo '\01\03\03\07')
usage_error () {
  printf >&2 "\n[error] $@\n"
  exit 2
}
if [ "$#" -gt 0 ] ; then
  set -- "$@" "$EOL"
  while [ "$1" != "$EOL" ] ; do
    opt="$1"
    shift
    case "$opt" in

      ######################################
      ### BEGIN: PROCESS COMMAND OPTIONS ###
      ######################################

      # Standard flags. Note that DDEV provides "--help" (usage) automatically.
      # Support multiple "v" flags.
      -v | --verbose ) [ $verbose ] && verbose="${verbose}v" || verbose="-v" ;;
      -y | --yes     ) skip_prompts=1 ;;

      # Flags to enable steps that are disabled by default.
      -i | --import-db    ) can_import_db=1 ;;
      -e | --existing-sql ) existing_sql=1 ;;

      # Flags to skip steps that are enabled by default.
      -G | --no-git-pull ) no_git_pull=1 ;;
      -R | --no-restart  ) no_restart=1 ;;
      -C | --no-composer ) no_composer=1 ;;
      -A | --no-assets   ) no_assets=1 ;;
      -U | --no-update   ) no_update=1 ;;
      -L | --no-login    ) no_login=1 ;;

      ####################################
      ### END: PROCESS COMMAND OPTIONS ###
      ####################################

      # Don't modify these.
      -|''|[^-]*) set -- "$@" "$opt" ;;                                            # positional parameter, rotate to the end
      --*=*)      set -- "${opt%%=*}" "${opt#*=}" "$@" ;;                          # convert '--name=arg' to '--name' 'arg'
      -[^-]?*)    set -- $(echo "${opt#-}" | sed 's/\(.\)/ -\1/g') "$@" ;;         # convert '-abc' to '-a' '-b' '-c'
      --)         while [ "$1" != "$EOL" ] ; do set -- "$@" "$1" ; shift ; done ;; # process remaining arguments as positional
      -*)         usage_error "Unknown option: '$opt'" ;;                          # catch misspelled options
      *)          usage_error "This should never happen ($opt)" ;;                 # sanity test for previous patterns
    esac
  done
  shift
fi

# Helper functions to decide whether a step can be executed.
can_skip_prompts   () { [ $skip_prompts  -eq 1 ] ; }
can_change_branch  () { [ -n "$branch"         ] ; }
can_update_git     () { [ $no_git_pull   -eq 0 ] ; }
can_restart_ddev   () { [ $no_restart    -eq 0 ] ; }
can_build_composer () { [ $no_composer   -eq 0 ] ; }
can_build_assets   () { [ $no_assets     -eq 0 ] ; }
can_import_db      () { [ $can_import_db -eq 1 ] ; }
can_skip_download  () { [ $existing_sql  -eq 1 ] ; }
can_update_drupal  () { [ $no_update     -eq 0 ] ; }
can_log_in         () { [ $no_login      -eq 0 ] ; }

# Helper function to prompt user for confirmation before proceeding.
confirm () {
  question="$1"
  help_text="$2"
  printf "\n$question (yes/no) [yes]: \n"
  if can_skip_prompts ; then
    echo "> yes"
  else
    read -p "> " -r
    printf '\n'
    case $(echo "$REPLY" | tr '[A-Z]' '[a-z]') in
      # On "y", "yes", or no input (default action), okay to proceed (no exit).
      yes | y | "" ) ;;
      # Any other response...
      * )
        if [ -n "$help_text" ] ; then
          echo "$help_text"
        fi
        exit 0
        ;;
    esac
  fi
}

# Use the first "positional parameter" as git branch. Note: All the options
# have been popped from the args list, so only positional parameters are left.
branch="$1"

# Ensure no other positional parameters were passed.
if [ "$#" -gt 1 ] ; then
  usage_error "This command only takes one argument (git branch name), got \"$@\""
fi

# Check for invalid options combinations.
if can_skip_download && (! can_import_db) ; then
  usage_error 'The "--existing-sql" option requires "--import-db".'
fi

# Make sure an existing database file is present, if requested.
db_dump_exists () { [ -f "${DDEV_APPROOT}/files/private/db.sql" ] ; }
if can_import_db && can_skip_download && (! db_dump_exists) ; then
  usage_error \
    'There is no previously-downloaded database dump. Rerun this command without "--existing-sql" to download a new file.'
fi

# Confirm reverting Drupal configuration changes.
has_config_changes () { ! ddev task drupal:config:check > /dev/null 2>&1 ; }
if can_update_drupal && has_config_changes ; then
  printf '\nYour local environment has some Drupal configuration overrides:\n\n'
  ddev drush config:status
  confirm \
    'Discard these configuration overrides and proceed?' \
    'To preserve configuration changes, export them to code with "drush config:export", and either commit them to a different/temporary branch, or stash the changes with "git stash".'
fi

# Confirm importing the database.
if can_import_db ; then
  confirm \
    'Importing the database replaces all content in your Drupal DB. Okay to discard local content changes?' \
    'To skip the database import step, rerun this command without the "--import-db" option.'
fi

# Helper function to print command before executing it.
announce () {
  step_is_allowed=$1
  step="${@:2}"
  # Append verbose flag to arguments.
  if $step_is_allowed ; then
    # Print the command first.
    printf "\n\$ $step"
    # Perform the step (execute the command).
    $step
    printf '\n'
  elif [ $verbose ] ; then
    echo "[info] Skipping \"$step\""
  fi
}

# Abort the rest of the script if any command fails from here onward.
set -e

# Steps to refresh.
announce can_change_branch   git fetch
announce can_change_branch   git checkout "$branch"
announce can_update_git      git pull
announce can_restart_ddev    ddev restart
announce can_build_composer  ddev task drupal:composer:development
announce can_build_assets    ddev task assets
# @todo https://github.com/Lullabot/drainpipe/issues/60
# announce can_skip_download   ddev task acquia:fetch-db
# announce can_import_db       ddev task drupal:import-db
announce can_update_drupal   ddev task drupal:update
announce can_log_in          ddev login
```

**Comment by hawkeyetwolf** [comment]
bump @justafish =D

**Comment by justafish** [comment]
@hawkeyetwolf apologies, I'm definitely missing something here! What's the difference between these two?

```
has_config_changes () { ! ddev task test:config > /dev/null 2>&1 ; }
```

vs 

```
has_config_changes () { ! ddev task drupal:config:check > /dev/null 2>&1 ; }
```

Is it that you're trying to get a more specific error code than `1`?

**Comment by hawkeyetwolf** [comment]
> Is it that you're trying to get a more specific error code than 1?

Yes! That's it exactly, thank you for deducing it succinctly. That way we can take action based on whether there are config changes or not.

**Comment by justafish** [comment]
@hawkeyetwolf there will always be config changes present if the exit code isn't `0`, the code returned from the snippet `drush config:status --format=string | wc -w` just represents how many configs have changed (multiplied by 2 because of the output format from `config:status`).

**Comment by hawkeyetwolf** [comment]
> > Is it that you're trying to get a more specific error code than 1?
>
> Yes! That's it exactly, thank you for deducing it succinctly. That way we can take action based on whether there are config changes or not.

This was a lie 😆 It's been a while since I wrote it and had to go back and rediscover why we want this.

The _real_ reason is so that we can have a quicker check. The `test:config` runs config status twice. We want a quick check, perform some steps of our own, and then output the config diff separately.

**Comment by hawkeyetwolf** [comment]
This from my original explanation:
> But I wanted just the first half of it, so I can do additional work if there are config changes.

**Comment by justafish** [comment]
@hawkeyetwolf here you go: https://github.com/Lullabot/drainpipe-dev/pull/41

**Pull request closed without merging**
