### PR TITLE
Specify drainpipe-sass script interpreter

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/Lullabot/drainpipe/issues/176

### CODE REVIEW

**Comment by deviantintegral** [comment]
I think the test failures are unrelated to this PR.

**Comment by pjudge** [comment]
Chiming in to say I ran into this exact issue with adding Drainpipe to a local test site. I employed @quicksketch 's fix and it worked. 👍

**Comment by deviantintegral** [comment]
Hopefully updating from main fixes the failing job.

@justafish not sure if this could use a test of some kind. If so, perhaps you and @pjudge could collaborate on it?

**Comment by justafish** [comment]
Thanks!

**Review by justafish — APPROVED** [review]

**Pull request merged**
